/*
    Name: Connie Huang
    Last modified: 2023-04-01
    Tutorial followed: https://youtu.be/DLAIYSMYy2g
    Comments generated by ChatGPT
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Pickup : MonoBehaviour
{
    private Inventory inventory; // reference to the Inventory component of the player
    public GameObject itemButton; // the button that represents the item in the inventory

    private void Start()
    {
        // get a reference to the Inventory component of the player
        inventory = GameObject.FindGameObjectWithTag("Player").GetComponent<Inventory>();
        //inventory = GameObject.FindGameObjectWithTag("player").GetComponent<Inventory>();
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player")) // check if the player has collided with the pickup object
        //if (other.CompareTag("player")) // check if the player has collided with the pickup object
        {
            Debug.Log("Player collide with object");
            // spawn the item button at the first available inventory slot
            for (int i = 0; i < inventory.slots.Length; i++) // loop through all inventory slots
            {
                if (inventory.isFull[i] == false) // check if the current slot is empty
                {
                    // mark the current slot as full
                    inventory.isFull[i] = true;

                    // instantiate the item button at the current slot's position and rotation, as a child of the slot
                    Instantiate(itemButton, inventory.slots[i].transform.position, inventory.slots[i].transform.rotation, inventory.slots[i].transform);

                    // destroy the pickup object
                    Destroy(gameObject);

                    // exit the loop, since the item has been added to the inventory
                    break;
                }
            }
        }
    }
}
