/*
    Name: Connie Huang
    Last modified: 2023-04-01
    Tutorial followed: https://youtu.be/DLAIYSMYy2g
    Comments generated by ChatGPT
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Slot : MonoBehaviour
{
    private Inventory inventory; // reference to the inventory component
    public int i; // the index of this slot

    private void Start()
    {
        inventory = GameObject.FindGameObjectWithTag("Player").GetComponent<Inventory>(); // get a reference to the inventory component on the player object
    }

    private void Update()
    {
        // check if this slot is empty and update the inventory accordingly
        if (transform.childCount <= 0)
        {
            inventory.isFull[i] = false;
        }
    }

    public void DropItem()
    {
        // loop through all the child objects of this slot and drop them
        foreach (Transform child in transform)
        {
            // call the SpawnDroppedItem() method on the child's Spawn component to drop the item
            child.GetComponent<Spawn>().SpawnDroppedItem();

            // destroy the child object (the item) after it's been dropped
            GameObject.Destroy(child.gameObject);
        }
    }
}
