/*
    Name: Connie Huang
    Last modified: 2023-04-07
    Tutorial followed: https://youtu.be/DLAIYSMYy2g
    Comments generated by ChatGPT then modified
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Spawn : MonoBehaviour
{
    private Transform player; // the player's transform
    public GameObject item; // the item to be spawned

    private void Start()
    {
        // set the player transform
        player = GameObject.FindGameObjectWithTag("Player").transform;
    }

    public void SpawnDroppedItem()
    {
        // set the position where the item will be spawned (behind the player on the z-axis)
        Vector3 playerPos = new Vector3(player.position.x + 1, player.position.y + 0.5f, player.position.z + 1f); 

        // instantiate the item at the set position and with no rotation
        Instantiate(item, playerPos, Quaternion.identity); 
    }
}
