/*
    Name: Connie Huang
    Last modified: 2023-04-01
    Tutorial followed: https://youtu.be/DLAIYSMYy2g
    Comments generated by ChatGPT
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Spawn : MonoBehaviour
{
    private Transform player; // the player's transform
    public GameObject item; // the item to be spawned

    private void Start()
    {
        player = GameObject.FindGameObjectWithTag("Player").transform; // set the player transform
    }

    public void SpawnDroppedItem()
    {
        Vector3 playerPos = new Vector3(player.position.x, player.position.y + 1, player.position.z + 1f); // set the position where the item will be spawned (behind the player on the z-axis)
        Instantiate(item, playerPos, Quaternion.identity); // instantiate the item at the set position and with no rotation
    }
}
